# ~/.config/lazygit/config.yml

gui:
  theme:
    activeBorderColor:
      - 255 51 102 # Love
    inactiveBorderColor:
      - 66 71 100 # Subtle
    optionsTextColor:
      - 224 220 255 # Text
    selectedLineBgColor:
      - 44 47 64 # Overlay
    selectedLineFgColor:
      - 232 231 232 # Base
    unselectedLineBgColor:
      - 30 32 46 # Surface
    unselectedLineFgColor:
      - 224 220 255 # Text
    diffTerminalColor:
      - 255 51 102 # Love
    diffTerminalFgColor:
      - 232 231 232 # Base
    inlineDiffColor:
      - 44 47 64 # Overlay
    inlineDiffBgColor:
      - 66 71 100 # Subtle
    contextBgColor:
      - 30 32 46 # Surface
    contextFgColor:
      - 82 87 117 # Muted
    panelBgColor:
      - 30 32 46 # Surface
    panelFgColor:
      - 224 220 255 # Text
    panelBorderColor:
      - 66 71 100 # Subtle
    mainBgColor:
      - 232 231 232 # Base
    mainFgColor:
      - 30 32 46 # Surface
    secondaryTextColor:
      - 82 87 117 # Muted
    fileTreeFolderColor:
      - 186 176 232 # Iris
    branchTextColor:
      - 255 51 102 # Love
    linkTextColor:
      - 255 221 89 # Gold
    borderColor:
      - 66 71 100 # Subtle
    textColor:
      - 224 220 255 # Text
    subPanelBgColor:
      - 30 32 46 # Surface
    subPanelFgColor:
      - 224 220 255 # Text
    mergeConflictBgColor:
      - 255 51 102 # Love
    mergeConflictFgColor:
      - 224 220 255 # Text

