# ~/.config/lazydocker/config.yml

gui:
  theme:
    activeBorderColor:
      - 174 129 219 # Purple (Rose Pine)
    inactiveBorderColor:
      - 100 130 145 # Dark Aqua (Rose Pine)
    optionsTextColor:
      - 129 161 193 # Light Aqua (Rose Pine)
    selectedLineBgColor:
      - 255 184 209 # Light Pink (Rose Pine)
    selectedLineFgColor:
      - 250 250 238 # Cream (Rose Pine)
    unselectedLineBgColor:
      - 37 43 49 # Dark Base (Rose Pine)
    unselectedLineFgColor:
      - 209 216 232 # Light Grey (Rose Pine)
    diffTerminalColor:
      - 102 133 153 # Aqua (Rose Pine)
    diffTerminalFgColor:
      - 255 184 209 # Light Pink (Rose Pine)
    inlineDiffColor:
      - 102 133 153 # Aqua (Rose Pine)
    inlineDiffBgColor:
      - 255 184 209 # Light Pink (Rose Pine)
    contextBgColor:
      - 255 184 209 # Light Pink (Rose Pine)
    contextFgColor:
      - 100 130 145 # Dark Aqua (Rose Pine)
    panelBgColor:
      - 37 43 49 # Dark Base (Rose Pine)
    panelFgColor:
      - 100 130 145 # Dark Aqua (Rose Pine)
    panelBorderColor:
      - 129 161 193 # Light Aqua (Rose Pine)
    mainBgColor:
      - 37 43 49 # Dark Base (Rose Pine)
    mainFgColor:
      - 250 250 238 # Cream (Rose Pine)
    secondaryTextColor:
      - 100 130 145 # Dark Aqua (Rose Pine)
    fileTreeFolderColor:
      - 211 134 155 # Red (Rose Pine)
    branchTextColor:
      - 255 184 209 # Light Pink (Rose Pine)
    linkTextColor:
      - 167 244 178 # Green (Rose Pine)
    borderColor:
      - 129 161 193 # Light Aqua (Rose Pine)
    textColor:
      - 209 216 232 # Light Grey (Rose Pine)
    subPanelBgColor:
      - 255 184 209 # Light Pink (Rose Pine)
    subPanelFgColor:
      - 209 216 232 # Light Grey (Rose Pine)
    mergeConflictBgColor:
      - 211 134 155 # Red (Rose Pine)
    mergeConflictFgColor:
      - 209 216 232 # Light Grey (Rose Pine)

keybindings:
  - description: "Start selected container"
    key: "Ctrl-s"
    action: "start_container"
  - description: "Stop selected container"
    key: "Ctrl-x"
    action: "stop_container"
  - description: "Restart selected container"
    key: "Ctrl-r"
    action: "restart_container"
  - description: "Create image from container"
    key: "Ctrl-i"
    action: "create_image"
  - description: "Navigate up"
    key: "k"
    action: "up"
  - description: "Navigate down"
    key: "j"
    action: "down"
  - description: "Page up"
    key: "Ctrl-b"
    action: "page_up"
  - description: "Page down"
    key: "Ctrl-f"
    action: "page_down"
  - description: "Go to top"
    key: "g"
    action: "top"
  - description: "Go to bottom"
    key: "G"
    action: "bottom"
  - description: "Refresh"
    key: "r"
    action: "refresh"
  - description: "Quit"
    key: "q"
    action: "quit"
  - description: "Toggle details"
    key: "enter"
    action: "toggle_details"
  - description: "Command mode"
    key: ":"
    action: "command_mode"
  - description: "Search"
    key: "/"
    action: "search"
  - description: "Clear search"
    key: "Esc"
    action: "clear_search"
  - description: "Help (Show keybindings)"
    key: "h"
    action: "help"
  - description: "Reload"
    key: "Ctrl-r"
    action: "reload"
  - description: "Clear screen"
    key: "Ctrl-l"
    action: "clear_screen"
  - description: "Copy selected"
    key: "Ctrl-c"
    action: "copy_selected"
  - description: "Paste"
    key: "Ctrl-v"
    action: "paste"
  - description: "Change scroll"
    key: "Tab"
    action: "change_scroll"
