#!/usr/bin/env bash

command -v jq >/dev/null 2>&1 || {
	echo >&2 "Program 'jq' required but it is not installed. Aborting."
	exit 1
}
command -v curl >/dev/null 2>&1 || {
	echo >&2 "Program 'curl' required but is not installed. Aborting."
	exit 1
}

# OpenWeather API key (replace with your actual API key)
APIKEY="cbba78fc1595a2610671185490bb3ad3"

# Paramakudi City ID (ID for Paramakudi)
CITY_ID="1260309"

# URL to fetch the weather data
URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"

# Fetch the weather data
WEATHER_RESPONSE=$(timeout --signal=1 2s curl -s "${URL}") || exit 1

# Parse weather information
WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
WIND_DIR=$(echo "$WEATHER_RESPONSE" | jq '.wind.deg')
WIND_SPEED=$(echo "$WEATHER_RESPONSE" | jq '.wind.speed')

# Calculate wind speed in km/h
WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")

# Calculate wind direction
WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
DIR_ARRAY=(N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N)
WIND_DIR=${DIR_ARRAY[WIND_DIR]}

# Set appropriate weather icon
case $WEATHER_CONDITION in
'Clouds')
	WEATHER_ICON=""
	;;
'Rain')
	WEATHER_ICON=""
	;;
'Snow')
	WEATHER_ICON=""
	;;
*)
	WEATHER_ICON=""
	;;
esac

# Output the weather information
echo "${WEATHER_ICON}  ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
