
[env]

[window]
padding = { x = 2, y = 2 }
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
opacity = 0.6

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0

[cursor]
style = "Block"
blink_interval = 500

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "K", mods = "Control|Shift", action = "ScrollPageUp" },
  { key = "J", mods = "Control|Shift", action = "ScrollPageDown" }
]

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[mouse]
hide_when_typing = true

[colors]
[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.normal]
black = "0x191724"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0xc4a7e7"
magenta = "0xeb6f92"
cyan = "0x9ccfd8"
white = "0xe0def4"

[colors.bright]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0xc4a7e7"
magenta = "0xeb6f92"
cyan = "0x9ccfd8"
white = "0xe0def4"

[colors.dim]
black = "0x1f1d2e"
red = "0xb4637a"
green = "0x61849c"
yellow = "0xd89760"
blue = "0xa06fd4"
magenta = "0xb4637a"
cyan = "0x61849c"
white = "0x908caa"

[terminal]

